# Generated by Django 2.2.4 on 2019-08-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine',
            field=models.SmallIntegerField(),
        ),
    ]
