# Generated by Django 2.2.16 on 2020-11-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='symptoms',
            field=models.ManyToManyField(related_name='encounters', to='patient.Symptom'),
        ),
    ]
