# Generated by Django 2.2.4 on 2019-08-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20190818_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine',
            field=models.CharField(max_length=40),
        ),
    ]
