# Generated by Django 2.2.4 on 2019-08-19 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20190818_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examination',
            old_name='Resp_Rate',
            new_name='resp_rate',
        ),
    ]
