# Generated by Django 2.2.4 on 2019-08-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20190813_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
