# Generated by Django 2.2.4 on 2019-08-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20190819_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='lifestyle',
            field=models.TextField(),
        ),
    ]
