# Generated by Django 2.2.4 on 2019-08-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='medicines',
            field=models.ManyToManyField(to='patient.Medicine'),
        ),
    ]
