# Generated by Django 2.2.4 on 2019-08-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_encounter_medicines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='medicines',
            field=models.ManyToManyField(null=True, to='patient.Medicine'),
        ),
    ]
