# Generated by Django 2.2.4 on 2019-08-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_auto_20190814_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='medicines',
            field=models.ManyToManyField(blank=True, null=True, to='patient.Medicine'),
        ),
    ]
