# Generated by Django 2.2.4 on 2019-08-14 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_auto_20190814_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='examination',
        ),
        migrations.AddField(
            model_name='examination',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Patient'),
        ),
    ]
