# Generated by Django 2.2.4 on 2019-08-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_auto_20190814_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
